version: '3.8'
services:
  serve:
    build: .
    container_name: feedbook
    command: python -m main
    ports:
      - '8500:8500'
    restart: always
  db:
    image: postgres
    container_name: feedbook_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # need this??
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init_data.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
